name: chat_app_dev

services:
  postgres:
    image: postgres:14
    container_name: chat_app_postgres_dev
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: pizza
      POSTGRES_PASSWORD: 123456
    ports:
      - "5437:5432"
    volumes:

      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6-alpine
    container_name: chat_app_redis_dev
    ports:
      - "6379:6379"