name: chat_app

services:
  nginx:
    image: nginx:latest
    container_name: chat_app_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chat_app_1
      - chat_app_2

  chat_app_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_app_1
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis

  chat_app_2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_app_2
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14
    container_name: chat_app_postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: pizza
      POSTGRES_PASSWORD: 123456
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6-alpine
    container_name: chat_app_redis
    ports:
      - "6385:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: